- name: installation of apache2  package
  apt:
    name: apache2
    state: latest
  notify:
    - start_apache2
  tags:
    - install

- name: enable ufw
  ufw:
    state: enabled
    policy: allow

- name: add port in ufw debian 
  ufw:
    rule: allow
    port: '80'
    proto: tcp
     
  


