---
# handlers file for /root/ansible/roles/apache
#
#

- name: start_apache2
  service:
    name: apache2
    state: started 
    enabled: true
- name: restart_apache2
  service:
    name: apache2
    state: restarted
    enabled: true


