---
# handlers file for /root/ansible/roles/apache
#
#

- name: start_apache
  service:
    name: httpd
    state: started 
    enabled: true
- name: restart_apache
  service:
    name: httpd
    state: restarted
    enabled: true

- name: start_firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: firewalld_reload
  command: firewalld-cmd --reload




